services:
  invoicerr:
    image: imprevisible/invoicerr:latest
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://invoicerr:invoicerr@invoicerr_db:5432/invoicerr_db
    depends_on:
      - invoicerr_db

  invoicerr_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: invoicerr
      POSTGRES_PASSWORD: invoicerr
      POSTGRES_DB: invoicerr_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local