  name: invoiceerr-backend-dev

  services:
    database-postgresql:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - '5432:5432'
      volumes:
        - docker-postgres:/var/lib/postgresql/data


  volumes:
    docker-postgres: