name: Cypress Tests

on:
  push:
    branches: [main]
  release:
    types: [ "created" ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres-test:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: invoicerr_test
        ports:
          - "5433:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Install e2e dependencies
        run: |
          cd e2e
          npm ci

      - name: Wait for DB
        run: npx wait-on tcp:5433 --timeout 60

      - name: Run backend, frontend & tests
        run: |
          (cd $GITHUB_WORKSPACE/backend && npm run start:test > /dev/null 2>&1 &)
          (cd $GITHUB_WORKSPACE/frontend && npm run start:test > /dev/null 2>&1 &)
          (cd $GITHUB_WORKSPACE/e2e && npm run e2e:run)
