name: Publish Docker Image to GitHub Container Registry

on:
  release:
    types: [ "created" ]
  push:
    branches:
      - test/workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: echo "REPO_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set image tags and cache reference
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            # Pour les releases (tags)
            TAG=${GITHUB_REF#refs/tags/}
            echo "IMAGE_TAGS=ghcr.io/${REPO_NAME_LOWER}:${TAG},ghcr.io/${REPO_NAME_LOWER}:latest" >> $GITHUB_ENV
            echo "CACHE_REF=release" >> $GITHUB_ENV
            echo "Build type: Release (tag: ${TAG})"
          elif [[ "${GITHUB_REF}" == refs/heads/test/workflow ]]; then
            # Pour la branche test/workflow spécifiquement
            echo "IMAGE_TAGS=ghcr.io/${REPO_NAME_LOWER}:test-workflow" >> $GITHUB_ENV
            echo "CACHE_REF=test-workflow" >> $GITHUB_ENV
            echo "Build type: Test workflow branch"
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Pour les autres branches (au cas où)
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SAFE_BRANCH_NAME=${BRANCH_NAME//\//-}
            echo "IMAGE_TAGS=ghcr.io/${REPO_NAME_LOWER}:${SAFE_BRANCH_NAME}" >> $GITHUB_ENV
            echo "CACHE_REF=branch-${SAFE_BRANCH_NAME}" >> $GITHUB_ENV
            echo "Build type: Other branch (${BRANCH_NAME})"
          else
            # Fallback
            echo "IMAGE_TAGS=ghcr.io/${REPO_NAME_LOWER}:latest" >> $GITHUB_ENV
            echo "CACHE_REF=default" >> $GITHUB_ENV
            echo "Build type: Default"
          fi

      - name: Display cache configuration
        run: |
          echo "🚀 Cache configuration:"
          echo "  Cache reference: ${{ env.CACHE_REF }}"
          echo "  Image tags: ${{ env.IMAGE_TAGS }}"
          echo "  Git ref: ${GITHUB_REF}"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 8

      - name: Check existing Docker cache
        run: |
          echo "🔍 Checking existing cache for scope: ${{ env.CACHE_REF }}"
          docker buildx du || true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,mode=max,scope=${{ env.CACHE_REF }}
          cache-to: type=gha,mode=max,scope=${{ env.CACHE_REF }}

      - name: Display build summary
        run: |
          echo "✅ Build completed successfully!"
          echo "  Images pushed: ${{ env.IMAGE_TAGS }}"
          echo "  Cache scope used: ${{ env.CACHE_REF }}"